openapi: 3.0.1
info:
  title: Product API
  description: "API для управления продуктами"
  version: 1.0.0
paths:
  /:
    get:
      tags:
        - General
      summary: Read Root
      operationId: read_root
      responses:
        '200':
          description: Приветственное сообщение
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /api/products:
    get:
      tags:
        - Products
      summary: Получить список всех товаров
      operationId: get_products
      responses:
        '200':
          description: Успешный ответ
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

    post:
      tags:
        - Products
      summary: Создать новый товар
      operationId: create_product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateProduct'
      responses:
        '200':
          description: Товар создан
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '422':
          $ref: '#/components/responses/ValidationError'

    put:
      tags:
        - Products
      summary: Редактировать существующий товар
      operationId: edit_product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateProduct'
      responses:
        '200':
          description: Товар обновлён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Товар не найден
        '422':
          $ref: '#/components/responses/ValidationError'

  /api/products/{id}:
    get:
      tags:
        - Products
      summary: Получить товар по ID
      operationId: get_product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Товар найден
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Товар не найден
        '422':
          $ref: '#/components/responses/ValidationError'

    delete:
      tags:
        - Products
      summary: Удалить товар по ID
      operationId: delete_product
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Товар удалён
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Товар не найден
        '422':
          $ref: '#/components/responses/ValidationError'

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
          format: float

    CreateProduct:
      type: object
      required:
        - name
        - price
      properties:
        name:
          type: string
        price:
          type: number
          format: float

    UpdateProduct:
      type: object
      required:
        - id
        - name
        - price
      properties:
        id:
          type: string
        name:
          type: string
        price:
          type: number
          format: float

    ValidationError:
      type: object
      properties:
        loc:
          type: array
          items:
            anyOf:
              - type: string
              - type: integer
        msg:
          type: string
        type:
          type: string
      required:
        - loc
        - msg
        - type

  responses:
    ValidationError:
      description: Ошибка валидации
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
