# coding: utf-8

"""
    Product API

    API для управления продуктами

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from endpoints.apis.general_api import router as GeneralApiRouter
from endpoints.apis.products_api import router as ProductsApiRouter

app = FastAPI(
    title="Product API",
    description="API для управления продуктами",
    version="1.0.0",
)

app.include_router(GeneralApiRouter)
app.include_router(ProductsApiRouter)
